// 政治家個人のデータベース
// url が設定されているものだけ検索結果に表示される
const politicians = [
    {
        id: "takaichi-sanae",
        name: "高市 早苗",
        kana: "たかいち さなえ",
        party: "自民党",
        role: "第104・105代 内閣総理大臣",
        area: "奈良2区（11選）",
        photo: "https://upload.wikimedia.org/wikipedia/commons/3/32/Sanae_Takaichi_portrait_%28HD%29_%28cropped_1%29.jpg",
        url: "politicians/takaichi-sanae/index.html",
        baseLikes: 5240,
        tags: ["高市", "高市早苗", "経済安保", "積極財政", "防衛", "奈良", "自民党", "サナエノミクス", "たかいち", "神戸大学", "松下政経塾"],
        desc: "神戸大学経営学部卒、松下政経塾を経て国政へ。総務大臣、経済安全保障担当大臣、自民党政調会長などを歴任。"
    },
    {
        id: "yoshimura-hirofumi",
        name: "吉村 洋文",
        kana: "よしむら ひろふみ",
        party: "大阪維新の会",
        role: "大阪府知事",
        area: "大阪府",
        photo: "https://upload.wikimedia.org/wikipedia/commons/f/f0/%E5%A4%A7%E9%98%AA%E5%BA%9C_%E7%9F%A5%E4%BA%8B_%E5%90%89%E6%9D%91%E6%B4%8B%E6%96%87_%28cropped%29.jpg",
        url: "politicians/yoshimura-hirofumi/index.html",
        baseLikes: 6830,
        tags: ["吉村", "吉村洋文", "よしむら", "大阪府知事", "大阪維新の会", "維新", "大阪市長", "九州大学", "公約達成度"],
        desc: "九州大学法学部卒、弁護士を経て大阪市会議員、衆議院議員、大阪市長、大阪府知事を歴任。2023年府政公約の達成度を蓄積。"
    },
    {
        id: "yamada-miki",
        name: "山田 みき",
        kana: "やまだ みき",
        party: "自民党",
        role: "東京1区候補",
        area: "東京都第1区",
        photo: "https://miki-yamada.com/wp-content/themes/yamada/profile/img/img1.jpg",
        url: "politicians/yamada-miki/index.html",
        baseLikes: 610,
        tags: ["山田みき", "やまだみき", "東京1区", "第51回衆議院選挙", "自民党", "外務大臣政務官", "環境副大臣", "東京大学", "コロンビア大学"],
        desc: "通商産業省、内閣官房、民間企業を経て国政へ。東京1区候補として経済成長、社会保障、安全保障、教育、都心税制を掲げる。"
    },
    {
        id: "kaieda-banri",
        name: "海江田 万里",
        kana: "かいえだ ばんり",
        party: "中道改革連合",
        role: "東京1区候補",
        area: "東京都第1区",
        photo: "https://kaiedabanri.jp/wp-content/uploads/2024/10/2021.jpg",
        url: "politicians/kaieda-banri/index.html",
        baseLikes: 830,
        tags: ["海江田万里", "かいえだばんり", "東京1区", "第51回衆議院選挙", "中道改革連合", "経済産業大臣", "民主党代表", "衆議院副議長"],
        desc: "経済産業大臣、民主党代表、衆議院副議長などを歴任。政治資金透明化、現役世代投資、社会保障改革を掲げる。"
    },
    {
        id: "yoshikawa-rina",
        name: "吉川 りな",
        kana: "よしかわ りな",
        party: "参政党",
        role: "東京1区候補",
        area: "東京都第1区",
        photo: "https://yoshikawa-rina.jp/official/wp-content/themes/wp_rina/assets/img/common/top-fv.jpg",
        url: "politicians/yoshikawa-rina/index.html",
        baseLikes: 490,
        tags: ["吉川りな", "よしかわりな", "東京1区", "第51回衆議院選挙", "参政党", "減税", "移民政策", "食料安全保障", "教育給付金"],
        desc: "看護師・保健師として医療現場に従事。参政党副代表として、減税、食料安全保障、移民政策、教育給付を掲げる。"
    },
    {
        id: "haruyama-asuka",
        name: "春山 あすか",
        kana: "はるやま あすか",
        party: "日本維新の会",
        role: "東京1区候補",
        area: "東京都第1区",
        photo: "https://o-ishin.jp/member/images/member/post_721.jpg",
        url: "politicians/haruyama-asuka/index.html",
        baseLikes: 440,
        tags: ["春山あすか", "はるやまあすか", "東京1区", "第51回衆議院選挙", "日本維新の会", "千代田区議", "DX", "消費税0", "東京大学大学院"],
        desc: "元千代田区議。IT、NPO、都市まちづくりの経験を背景に、食料品消費税0%、DX、教育自由化を掲げる。"
    },
    {
        id: "kuroda-asahi",
        name: "黒田 あさひ",
        kana: "くろだ あさひ",
        party: "日本共産党",
        role: "東京1区候補",
        area: "東京都第1区",
        photo: "https://image.jimcdn.com/app/cms/image/transf/dimension=550x10000:format=jpg/path/s52fad9203be38c65/image/i9f01f713bd5dc418/version/1768922365/image.jpg",
        url: "politicians/kuroda-asahi/index.html",
        baseLikes: 260,
        tags: ["黒田あさひ", "くろだあさひ", "東京1区", "第51回衆議院選挙", "日本共産党", "消費税5%", "最低賃金", "核兵器禁止条約", "選択的夫婦別姓"],
        desc: "日本共産党の東京1区候補。消費税減税、最低賃金引き上げ、外交による平和、人権・多様性を掲げる。"
    },
    {
        id: "aso-taro",
        name: "麻生 太郎",
        kana: "あそう たろう",
        party: "自民党",
        role: "副総裁",
        area: "福岡8区",
        photo: "https://www.jimin.jp/member/img/asou-tarou.jpg",
        url: "politicians/aso-taro/index.html",
        baseLikes: 3180,
        tags: ["麻生", "麻生太郎", "あそう", "自民党", "副総裁", "総理大臣", "財務大臣", "福岡"],
        desc: "第92代内閣総理大臣、財務大臣、外務大臣、党幹事長などを歴任。"
    },
    {
        id: "suzuki-shunichi",
        name: "鈴木 俊一",
        kana: "すずき しゅんいち",
        party: "自民党",
        role: "幹事長",
        area: "岩手2区",
        photo: "https://www.jimin.jp/member/img/suzuki-shunichi.jpg",
        url: "politicians/suzuki-shunichi/index.html",
        baseLikes: 1240,
        tags: ["鈴木", "鈴木俊一", "すずき", "自民党", "幹事長", "財務大臣", "岩手"],
        desc: "財務大臣、総務会長、環境大臣などを歴任。高市体制の幹事長。"
    },
    {
        id: "kobayashi-takayuki",
        name: "小林 鷹之",
        kana: "こばやし たかゆき",
        party: "自民党",
        role: "政務調査会長",
        area: "千葉2区",
        photo: "https://www.jimin.jp/member/img/kobayashi-takayuki.jpg",
        url: "politicians/kobayashi-takayuki/index.html",
        baseLikes: 1520,
        tags: ["小林", "小林鷹之", "こばやし", "自民党", "政調会長", "政務調査会長", "経済安全保障", "千葉"],
        desc: "経済安全保障担当大臣などを歴任。政務調査会長として政策立案を担う。"
    },
    {
        id: "arimura-haruko",
        name: "有村 治子",
        kana: "ありむら はるこ",
        party: "自民党",
        role: "総務会長",
        area: "比例代表",
        photo: "https://www.jimin.jp/member/img/arimura-haruko.jpg",
        url: "politicians/arimura-haruko/index.html",
        baseLikes: 880,
        tags: ["有村", "有村治子", "ありむら", "自民党", "総務会長", "参議院", "比例"],
        desc: "女性活躍・行政改革・少子化対策などの担当大臣を歴任。"
    },
    {
        id: "furuya-keiji",
        name: "古屋 圭司",
        kana: "ふるや けいじ",
        party: "自民党",
        role: "選挙対策委員長",
        area: "岐阜5区",
        photo: "https://www.jimin.jp/member/img/furuya-keiji.jpg",
        url: "politicians/furuya-keiji/index.html",
        baseLikes: 760,
        tags: ["古屋", "古屋圭司", "ふるや", "自民党", "選対委員長", "選挙対策委員長", "拉致問題", "岐阜"],
        desc: "国家公安委員長、拉致問題担当大臣、防災担当大臣などを歴任。"
    },
    {
        id: "tamaki-yuichiro",
        name: "玉木 雄一郎",
        kana: "たまき ゆういちろう",
        party: "国民民主党",
        role: "代表",
        area: "香川2区",
        photo: "https://new-kokumin.jp/wp-content/uploads/2020/11/member_img3.jpg",
        url: "politicians/tamaki-yuichiro/index.html",
        baseLikes: 8420,
        tags: ["玉木", "玉木雄一郎", "たまき", "国民民主党", "代表", "手取りを増やす", "年収の壁", "178万円", "ガソリン暫定税率", "香川", "高松高校", "東京大学", "ハーバード", "財務省"],
        desc: "香川県立高松高校、東京大学法学部、ハーバード大学大学院を経て大蔵省・財務省へ。国民民主党代表として年収の壁178万円、ガソリン暫定税率廃止などを追う。"
    },
    {
        id: "furukawa-motohisa",
        name: "古川 元久",
        kana: "ふるかわ もとひさ",
        party: "国民民主党",
        role: "代表代行",
        area: "愛知2区",
        photo: "https://new-kokumin.jp/wp-content/uploads/2020/11/member_img5.jpg",
        url: "politicians/furukawa-motohisa/index.html",
        baseLikes: 940,
        tags: ["古川", "古川元久", "ふるかわ", "国民民主党", "代表代行", "国対", "愛知", "東大", "大蔵省"],
        desc: "国家戦略担当大臣、経済財政政策担当大臣などを歴任。"
    },
    {
        id: "shimba-kazuya",
        name: "榛葉 賀津也",
        kana: "しんば かづや",
        party: "国民民主党",
        role: "幹事長",
        area: "静岡県",
        photo: "https://new-kokumin.jp/wp-content/uploads/2024/08/83adbecc191cd73da251eeec6cf245c0-scaled-e1738200045606.jpg",
        url: "politicians/shimba-kazuya/index.html",
        baseLikes: 1680,
        tags: ["榛葉", "榛葉賀津也", "しんば", "国民民主党", "幹事長", "防衛副大臣", "外務副大臣", "静岡"],
        desc: "防衛副大臣、外務副大臣を歴任。国民民主党幹事長。"
    },
    {
        id: "funayama-yasue",
        name: "舟山 康江",
        kana: "ふなやま やすえ",
        party: "国民民主党",
        role: "参議院議員会長",
        area: "山形県",
        photo: "https://new-kokumin.jp/wp-content/uploads/2020/11/member_img14.jpg",
        url: "politicians/funayama-yasue/index.html",
        baseLikes: 620,
        tags: ["舟山", "舟山康江", "ふなやま", "国民民主党", "参議院議員会長", "両院議員総会長", "農林水産省", "山形"],
        desc: "農林水産省出身。党政調会長を経て参議院議員会長兼両院議員総会長。"
    },
    {
        id: "hamaguchi-makoto",
        name: "浜口 誠",
        kana: "はまぐち まこと",
        party: "国民民主党",
        role: "政務調査会長",
        area: "比例区",
        photo: "https://new-kokumin.jp/wp-content/uploads/2021/03/bf7c646c5acc33a00f095dc8ec02c885.jpg",
        url: "politicians/hamaguchi-makoto/index.html",
        baseLikes: 480,
        tags: ["浜口", "浜口誠", "はまぐち", "国民民主党", "政調会長", "政務調査会長", "自動車総連", "トヨタ", "比例"],
        desc: "トヨタ自動車、自動車総連での経験を持つ参議院議員。政務調査会長。"
    },
    {
        id: "koizumi-shinjiro",
        name: "小泉 進次郎",
        kana: "こいずみ しんじろう",
        party: "自民党",
        role: "防衛大臣",
        area: "神奈川11区",
        photo: "https://www.jimin.jp/election/results/sousai24/img/profile/koizumi_shinjiro.png",
        url: "politicians/koizumi-shinjiro/index.html",
        baseLikes: 7200,
        tags: ["小泉進次郎", "こいずみしんじろう", "小泉", "自民党", "防衛大臣", "農林水産大臣", "環境大臣", "神奈川11区", "横須賀", "関東学院大学", "コロンビア大学", "CSIS", "小泉純一郎", "総裁選2024"],
        desc: "関東学院大学、米コロンビア大学大学院を経てCSIS研究員、秘書、衆院議員へ。環境大臣、衆院安全保障委員長、農林水産大臣を歴任し、高市内閣で防衛大臣。"
    },
    {
        id: "noda-yoshihiko",
        name: "野田 佳彦",
        kana: "のだ よしひこ",
        party: "中道改革連合",
        role: "顧問",
        area: "千葉14区",
        photo: "https://cdp-japan.jp/assets/images/leadership_election/2024/01_portrait.w768.jpg",
        url: "politicians/noda-yoshihiko/index.html",
        baseLikes: 4800,
        tags: ["野田佳彦", "のだよしひこ", "野田", "中道改革連合", "立憲民主党", "顧問", "元代表", "総理大臣", "首相", "千葉14区", "早稲田大学", "松下政経塾", "財務大臣", "民主党", "どじょう内閣", "政治改革"],
        desc: "早稲田大学政治経済学部、松下政経塾を経て千葉県議、衆議院議員へ。第95代内閣総理大臣、財務大臣、立憲民主党代表、中道改革連合共同代表を歴任。"
    },
    {
        id: "fujita-fumitake",
        name: "藤田 文武",
        kana: "ふじた ふみたけ",
        party: "日本維新の会",
        role: "共同代表",
        area: "大阪12区",
        photo: "https://o-ishin.jp/member/images/member/fujita_fumitake.jpg",
        url: "politicians/fujita-fumitake/index.html",
        baseLikes: 2100,
        tags: ["藤田文武", "ふじたふみたけ", "藤田", "日本維新の会", "維新", "共同代表", "幹事長", "大阪12区", "法政大学"],
        desc: "法政大学経済学部卒。音楽活動を経て政界へ。2019年衆院初当選。日本維新の会共同代表・国会議員団の長として党運営を担う。"
    },
    {
        id: "kamiya-souhei",
        name: "神谷 宗幣",
        kana: "かみや そうへい",
        party: "参政党",
        role: "代表",
        area: "参議院比例代表",
        photo: "https://sanseito.jp/nppoj/wp-content/themes/wp_310/images/bmember/kamiya_sohei.webp?20250910",
        url: "politicians/kamiya-souhei/index.html",
        baseLikes: 1900,
        tags: ["神谷宗幣", "かみやそうへい", "神谷", "参政党", "代表", "比例代表", "吹田市議", "関西大学", "参議院"],
        desc: "関西大学法科大学院修了。吹田市議を経て参政党を結党し、2022年参院選で比例代表から初当選。党代表・事務局長。"
    },
    {
        id: "hyakuta-naoki",
        name: "百田 尚樹",
        kana: "ひゃくた なおき",
        party: "日本保守党",
        role: "代表",
        area: "参議院比例代表",
        photo: "https://hoshuto.jp/contents/wp-content/uploads/2023/09/photo-hyakuta.jpg",
        url: "politicians/hyakuta-naoki/index.html",
        baseLikes: 3600,
        tags: ["百田尚樹", "ひゃくたなおき", "百田", "日本保守党", "代表", "参議院", "比例代表", "放送作家", "小説家", "永遠の0", "海賊とよばれた男"],
        desc: "放送作家・小説家として「永遠の０」「海賊とよばれた男」などを執筆。日本保守党代表として2025年参院選で比例代表から初当選。"
    },
    {
        id: "saito-tetsuo",
        name: "斎藤 鉄夫",
        kana: "さいとう てつお",
        party: "中道改革連合",
        role: "顧問",
        area: "中国比例",
        photo: "https://www.komei.or.jp/giin/img/giin_saito_tetsuo.jpg",
        url: "politicians/saito-tetsuo/index.html",
        baseLikes: 1450,
        tags: ["斎藤鉄夫", "さいとうてつお", "斎藤", "中道改革連合", "公明党", "顧問", "共同代表", "国土交通大臣", "広島", "中国比例", "衆議院"],
        desc: "東京工業大学大学院修了（工学博士）。環境大臣、国土交通大臣、公明党代表を歴任。中道改革連合共同代表を経て顧問。"
    },
    {
        id: "yamamoto-taro",
        name: "山本 太郎",
        kana: "やまもと たろう",
        party: "れいわ新選組",
        role: "代表（前参議院議員）",
        area: "れいわ新選組",
        photo: "https://reiwa-shinsengumi.com/wp-content/uploads/2022/05/yamamoto_taro_official.jpg",
        url: "politicians/yamamoto-taro/index.html",
        baseLikes: 6200,
        tags: ["山本太郎", "やまもとたろう", "山本", "れいわ新選組", "代表", "消費税廃止", "積極財政", "脱原発", "参議院", "比例代表", "俳優"],
        desc: "俳優出身。原発事故を機に政治活動を開始し2019年れいわ新選組を結成。消費税廃止・積極財政・脱原発を旗印に支持を集める。2026年1月、健康上の理由から参院議員を辞職し代表職を続投。"
    },
    {
        id: "oishi-akiko",
        name: "大石 あきこ",
        kana: "おおいし あきこ",
        party: "れいわ新選組",
        role: "共同代表（前衆議院議員）",
        area: "前・衆議院比例近畿",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Akiko_Oishi_%28cropped%29.jpg/440px-Akiko_Oishi_%28cropped%29.jpg",
        url: "politicians/oishi-akiko/index.html",
        baseLikes: 3400,
        tags: ["大石あきこ", "おおいしあきこ", "大石", "れいわ新選組", "共同代表", "消費税廃止", "大阪", "衆議院", "元大阪府職員"],
        desc: "元大阪府職員。2021年衆院選で初当選し、れいわ新選組共同代表として消費税廃止・ジェンダー平等・大阪維新対抗の旗手として活動。2026年衆院選で落選。"
    },
    {
        id: "koike-yuriko",
        name: "小池 百合子",
        kana: "こいけ ゆりこ",
        party: "無所属",
        role: "東京都知事",
        area: "東京都",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Yuriko_Koike_January_2026_%28cropped_1%29.jpg/500px-Yuriko_Koike_January_2026_%28cropped_1%29.jpg",
        url: "politicians/koike-yuriko/index.html",
        baseLikes: 7800,
        tags: ["小池百合子", "こいけゆりこ", "小池", "東京都知事", "東京", "都知事", "ゼロエミッション", "希望の党", "防衛大臣"],
        desc: "元防衛大臣・環境大臣。2016年東京都知事就任後、東京五輪・ゼロエミッション東京・子育て支援などを推進。2024年都知事選で3選。"
    },
    {
        id: "kishida-fumio",
        name: "岸田 文雄",
        kana: "きしだ ふみお",
        party: "自民党",
        role: "元・第100・101代 内閣総理大臣",
        area: "広島1区（11選）",
        photo: "https://kishida.gr.jp/wp-content/themes/new-theme/public/images/top/profile.png",
        url: "politicians/kishida-fumio/index.html",
        baseLikes: 4200,
        tags: ["岸田", "岸田文雄", "きしだ", "元首相", "総理大臣", "自民党", "広島", "防衛費増額", "GX", "NISA", "新しい資本主義", "少子化対策"],
        desc: "広島1区で11期当選。外務大臣を5年間務めた後、2021年に第100・101代内閣総理大臣に就任。防衛費増額・GX脱炭素電源法・NISA拡充・少子化対策を推進し、在任1094日で首相を退任。"
    },
    {
        id: "ishiba-shigeru",
        name: "石破 茂",
        kana: "いしば しげる",
        party: "自由民主党",
        role: "衆議院議員",
        area: "鳥取県第1区",
        photo: "https://www.jimin.jp/member/img/ishiba-shigeru.jpg",
        url: "politicians/ishiba-shigeru/index.html",
        baseLikes: 5600,
        tags: ["石破茂", "いしばしげる", "石破", "自民党", "前首相", "総理大臣", "防衛大臣", "地方創生", "鳥取", "安全保障"],
        desc: "第102・103代内閣総理大臣。防衛大臣・農林水産大臣・地方創生担当大臣などを歴任。安全保障・地方分権を軸とした政策で知られる。"
    },
    {
        id: "kono-taro",
        name: "河野 太郎",
        kana: "このう たろう",
        party: "自由民主党",
        role: "衆議院議員",
        area: "神奈川県第15区",
        photo: "https://www.jimin.jp/member/img/kouno-tarou.jpg",
        url: "politicians/kono-taro/index.html",
        baseLikes: 5100,
        tags: ["河野太郎", "このうたろう", "河野", "自民党", "デジタル大臣", "行政改革", "マイナンバー", "再生可能エネルギー", "外務大臣", "神奈川"],
        desc: "元デジタル大臣・外務大臣・防衛大臣。行政改革・マイナンバー推進・再生可能エネルギー推進を主導。2024年自民党総裁選に出馬。"
    },
    {
        id: "motegi-toshimitsu",
        name: "茂木 敏充",
        kana: "もてぎ としみつ",
        party: "自由民主党",
        role: "外務大臣",
        area: "栃木県第5区",
        photo: "https://www.kantei.go.jp/jp/content/motegi_toshimitsu_r.jpg",
        url: "politicians/motegi-toshimitsu/index.html",
        baseLikes: 4300,
        tags: ["茂木敏充", "もてぎとしみつ", "茂木", "自由民主党", "自民党", "外務大臣", "幹事長", "経済産業大臣", "経済再生担当大臣", "栃木5区", "東京大学", "ハーバード", "マッキンゼー"],
        desc: "東京大学、ハーバード大学大学院を経て丸紅、読売新聞、マッキンゼーへ。経産相、経済再生担当相、外相、自民党幹事長を歴任し、高市内閣で外務大臣。"
    },
    {
        id: "kamikawa-yoko",
        name: "上川 陽子",
        kana: "かみかわ ようこ",
        party: "自由民主党",
        role: "衆議院議員",
        area: "静岡県第1区",
        photo: "https://www.jimin.jp/member/img/kamikawa-yoko.jpg",
        url: "politicians/kamikawa-yoko/index.html",
        baseLikes: 3900,
        tags: ["上川陽子", "かみかわようこ", "上川", "自民党", "外務大臣", "法務大臣", "女性首相候補", "静岡", "外交"],
        desc: "元外務大臣・法務大臣。ハーバード大学大学院修了。外交・安全保障分野の実績と女性首相候補として注目される。"
    },
    {
        id: "saito-motohiko",
        name: "斎藤 元彦",
        kana: "さいとう もとひこ",
        party: "無所属",
        role: "兵庫県知事",
        area: "兵庫県",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Motohiko_Saito_%28cropped%2C_2%29.jpg/440px-Motohiko_Saito_%28cropped%2C_2%29.jpg",
        url: "politicians/saito-motohiko/index.html",
        baseLikes: 4200,
        tags: ["斎藤元彦", "さいとうもとひこ", "斎藤", "兵庫県知事", "兵庫", "知事", "維新", "不祥事", "再選"],
        desc: "元総務省官僚。2021年兵庫県知事就任。2024年に内部告発問題・不信任・失職を経て再選。地方行政と政治倫理の観点から全国的に注目される。"
    },
    {
        id: "onoda-kimi",
        name: "小野田 紀美",
        kana: "おのだ きみ",
        party: "自由民主党",
        role: "参議院議員",
        area: "岡山県",
        photo: "https://www.jimin.jp/member/img/onoda-kimi.jpg",
        url: "politicians/onoda-kimi/index.html",
        baseLikes: 2900,
        tags: ["小野田紀美", "おのだきみ", "小野田", "自民党", "参議院", "岡山", "日米ハーフ", "外交安保", "SNS"],
        desc: "米国生まれの日米ハーフ。岡山県選出の参議院議員として外交・安全保障・拉致問題に取り組む。SNSでの発信力と国際感覚で注目される。"
    },
    {
        id: "hanakado-hideyo",
        name: "花角 英世",
        kana: "はなかど ひでよ",
        party: "無所属（自民・公明推薦）",
        role: "新潟県知事",
        area: "新潟県",
        photo: "https://www.pref.niigata.lg.jp/site/chiji/img/chiji_photo.jpg",
        url: "politicians/hanakado-hideyo/index.html",
        baseLikes: 2100,
        tags: ["花角英世", "はなかどひでよ", "花角", "新潟県知事", "新潟", "知事", "原発", "柏崎刈羽", "人口減少", "農業"],
        desc: "元国土交通省官僚。2018年新潟県知事初当選、2022年2期目。柏崎刈羽原発の再稼働判断・人口減少対策を主な政策課題とし、2026年知事選が注目される。"
    },
    {
        id: "hiraguchi-hiroshi",
        name: "平口 洋",
        kana: "ひらぐち ひろし",
        party: "自由民主党",
        role: "法務大臣",
        area: "広島県第2区",
        photo: "https://www.jimin.jp/member/img/hiraguchi-hiroshi.jpg",
        url: "politicians/hiraguchi-hiroshi/index.html",
        baseLikes: 2800,
        tags: ["平口洋", "ひらぐちひろし", "平口", "自民党", "法務大臣", "高市内閣", "広島", "衆議院", "建設省", "国土交通"],
        desc: "東京大学法学部卒、元建設省官僚。広島2区で7期当選。2025年10月、高市内閣で初入閣（第111・112代法務大臣）。"
    },
    {
        id: "matsumoto-yohei",
        name: "松本 洋平",
        kana: "まつもと ようへい",
        party: "自由民主党",
        role: "文部科学大臣",
        area: "東京都第19区",
        photo: "https://www.jimin.jp/member/img/matsumoto-yohei.jpg",
        url: "politicians/matsumoto-yohei/index.html",
        baseLikes: 3200,
        tags: ["松本洋平", "まつもとようへい", "松本", "自民党", "文部科学大臣", "高市内閣", "東京19区", "衆議院", "教育", "三和銀行"],
        desc: "慶應義塾大学経済学部卒、元三和銀行員。東京19区で7期当選。2025年10月、高市内閣で初入閣（第33・34代文部科学大臣）。"
    },
    {
        id: "ueno-kenichiro",
        name: "上野 賢一郎",
        kana: "うえの けんいちろう",
        party: "自由民主党",
        role: "厚生労働大臣",
        area: "滋賀県第2区",
        photo: "https://www.jimin.jp/member/img/ueno-kenichiro.jpg",
        url: "politicians/ueno-kenichiro/index.html",
        baseLikes: 3000,
        tags: ["上野賢一郎", "うえのけんいちろう", "上野", "自民党", "厚生労働大臣", "高市内閣", "滋賀", "衆議院", "総務省", "社会保障"],
        desc: "京都大学法学部卒、元自治省官僚。滋賀2区で7期当選。財務副大臣などを歴任し、2025年10月高市内閣で初入閣（厚生労働大臣）。"
    },
    {
        id: "suzuki-norikazu",
        name: "鈴木 憲和",
        kana: "すずき のりかず",
        party: "自由民主党",
        role: "農林水産大臣",
        area: "山形県第2区",
        photo: "https://www.jimin.jp/member/img/suzuki-norikazu.jpg",
        url: "politicians/suzuki-norikazu/index.html",
        baseLikes: 2600,
        tags: ["鈴木憲和", "すずきのりかず", "鈴木", "自民党", "農林水産大臣", "高市内閣", "山形", "衆議院", "農水省", "農業"],
        desc: "東京大学法学部卒、元農林水産省官僚。山形2区で6期当選。2025年10月高市内閣で農林水産大臣に就任（73・74代）。食料安全保障・農業DXを推進。"
    },
    {
        id: "akazawa-ryosei",
        name: "赤澤 亮正",
        kana: "あかざわ りょうせい",
        party: "自由民主党",
        role: "経済産業大臣",
        area: "鳥取県第2区",
        photo: "https://www.jimin.jp/member/img/akazawa-ryosei.jpg",
        url: "politicians/akazawa-ryosei/index.html",
        baseLikes: 3500,
        tags: ["赤澤亮正", "あかざわりょうせい", "赤澤", "自民党", "経済産業大臣", "高市内閣", "鳥取", "衆議院", "運輸省", "GX", "原子力"],
        desc: "東京大学法学部卒・コーネル大MBA、元運輸省官僚。鳥取2区で8期当選。石破内閣で経済財政政策担当を経て、高市内閣で経済産業大臣に就任。"
    },
    {
        id: "kaneko-yasushi",
        name: "金子 恭之",
        kana: "かねこ やすし",
        party: "自由民主党",
        role: "国土交通大臣",
        area: "熊本県第4区",
        photo: "https://www.jimin.jp/member/img/kaneko-yasushi.jpg",
        url: "politicians/kaneko-yasushi/index.html",
        baseLikes: 2900,
        tags: ["金子恭之", "かねこやすし", "金子", "自民党", "国土交通大臣", "高市内閣", "熊本", "衆議院", "総務大臣", "インフラ"],
        desc: "早稲田大学商学部卒。熊本4区で9期当選。元総務大臣（岸田内閣）。2025年10月高市内閣で国土交通大臣に就任（2度目の入閣）。"
    },
    {
        id: "ishihara-hirotaka",
        name: "石原 宏高",
        kana: "いしはら ひろたか",
        party: "自由民主党",
        role: "環境大臣",
        area: "東京都第3区",
        photo: "https://www.jimin.jp/member/img/ishihara-hirotaka.jpg",
        url: "politicians/ishihara-hirotaka/index.html",
        baseLikes: 3100,
        tags: ["石原宏高", "いしはらひろたか", "石原", "自民党", "環境大臣", "高市内閣", "東京3区", "衆議院", "石原慎太郎", "脱炭素"],
        desc: "慶應義塾大学経済学部卒、元日本興業銀行員。東京3区で7期当選。石原慎太郎元都知事の三男。2025年10月高市内閣で初入閣（環境大臣）。"
    },
    {
        id: "kihara-minoru",
        name: "木原 稔",
        kana: "きはら みのる",
        party: "自由民主党",
        role: "内閣官房長官",
        area: "熊本県第1区",
        photo: "https://www.jimin.jp/member/img/kihara-minoru.jpg",
        url: "politicians/kihara-minoru/index.html",
        baseLikes: 4200,
        tags: ["木原稔", "きはらみのる", "木原", "自民党", "内閣官房長官", "高市内閣", "熊本", "衆議院", "防衛大臣", "安全保障"],
        desc: "早稲田大学卒、元日本航空勤務。熊本1区で7期当選。元防衛大臣（岸田内閣）。2025年10月高市内閣で内閣官房長官（第90・91代）に就任。"
    },
    {
        id: "matsumoto-hisashi",
        name: "松本 尚",
        kana: "まつもと ひさし",
        party: "自由民主党",
        role: "デジタル大臣",
        area: "千葉県第13区",
        photo: "https://www.jimin.jp/member/img/matsumoto-hisashi.jpg",
        url: "politicians/matsumoto-hisashi/index.html",
        baseLikes: 3800,
        tags: ["松本尚", "まつもとひさし", "松本", "自民党", "デジタル大臣", "高市内閣", "千葉", "衆議院", "医師", "ドクターヘリ", "コードブルー"],
        desc: "金沢大学医学部卒の外科医・救急医。日本医科大学教授・ドクターヘリ普及に尽力。ドラマ「コード・ブルー」医療監修者。2021年政界入りし3期目で高市内閣デジタル大臣。"
    },
    {
        id: "makino-takao",
        name: "牧野 たかお",
        kana: "まきの たかお",
        party: "自由民主党",
        role: "復興大臣",
        area: "静岡県（参議院）",
        photo: "https://www.jimin.jp/member/img/makino-takao.jpg",
        url: "politicians/makino-takao/index.html",
        baseLikes: 2400,
        tags: ["牧野たかお", "まきのたかお", "牧野", "自民党", "復興大臣", "高市内閣", "静岡", "参議院", "テレビ静岡", "復興"],
        desc: "早稲田大学法学部卒、元テレビ静岡記者。静岡県議3期を経て参議院4期。外務・国土交通副大臣を歴任し、2025年10月高市内閣で初入閣（復興大臣）。"
    },
    {
        id: "akama-jiro",
        name: "あかま 二郎",
        kana: "あかま じろう",
        party: "自由民主党",
        role: "国家公安委員長",
        area: "神奈川県第14区",
        photo: "https://www.jimin.jp/member/img/akama-jiro.jpg",
        url: "politicians/akama-jiro/index.html",
        baseLikes: 2700,
        tags: ["あかま二郎", "赤間二郎", "あかまじろう", "自民党", "国家公安委員長", "高市内閣", "神奈川", "衆議院", "総務副大臣", "防災"],
        desc: "立教大学卒・マンチェスター大学大学院修了。神奈川14区で7期当選。総務副大臣・内閣府副大臣を歴任。2025年10月高市内閣で初入閣（国家公安委員長）。"
    },
    {
        id: "kikawada-hitoshi",
        name: "黄川田 仁志",
        kana: "きかわだ ひとし",
        party: "自由民主党",
        role: "こども政策・少子化対策担当大臣",
        area: "埼玉県第3区",
        photo: "https://www.jimin.jp/member/img/kikawada-hitoshi.jpg",
        url: "politicians/kikawada-hitoshi/index.html",
        baseLikes: 2500,
        tags: ["黄川田仁志", "きかわだひとし", "黄川田", "自民党", "こども政策", "少子化対策", "高市内閣", "埼玉", "衆議院", "環境", "外交"],
        desc: "東京理科大学・メリーランド大学大学院修了。埼玉3区で6期当選。外務大臣政務官・内閣府副大臣を歴任。2025年10月高市内閣でこども政策・少子化対策担当大臣。"
    },
    {
        id: "kiuchi-minoru",
        name: "城内 実",
        kana: "きうち みのる",
        party: "自由民主党",
        role: "日本成長戦略・経済財政政策担当大臣",
        area: "静岡県第7区",
        photo: "https://www.jimin.jp/member/img/kiuchi-minoru.jpg",
        url: "politicians/kiuchi-minoru/index.html",
        baseLikes: 3400,
        tags: ["城内実", "きうちみのる", "城内", "自民党", "成長戦略", "経済財政政策", "高市内閣", "静岡", "衆議院", "外務省", "経済安全保障"],
        desc: "東京大学教養学部卒、元外務省官僚。天皇・首相のドイツ語通訳を担当。静岡7区で8期当選。石破内閣で経済安全保障担当、高市内閣で日本成長戦略・経済財政政策担当大臣。"
    }
];

window.politicians = politicians;
